# Generated by Django 6.0.7 on 2026-07-26 03:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título da receita', max_length=255, verbose_name='Título')),
                ('description', models.TextField(help_text='Descrição da receita', verbose_name='Descrição')),
                ('slug', models.SlugField(help_text='Slug da receita (gerado automaticamente a partir do título)', max_length=255, unique=True, verbose_name='Slug')),
                ('content', models.TextField(help_text='Modo de preparo da receita', verbose_name='Modo de preparo')),
                ('preparation_time', models.PositiveIntegerField(help_text='Tempo de preparo em minutos', verbose_name='Tempo de preparo (minutos)')),
                ('servings', models.PositiveIntegerField(help_text='Número de porções', verbose_name='Porções')),
                ('image', models.ImageField(blank=True, help_text='Imagem da receita', null=True, upload_to='recipe_images/', validators=[core.validators.validar_peso, core.validators.validar_tipo, core.validators.validar_dimensoes], verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
