# Generated by Django 6.0.7 on 2026-07-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(default='minutos', help_text='Unidade de tempo de preparo', max_length=20, verbose_name='Unidade de tempo de preparo'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings_unit',
            field=models.CharField(default='porções', help_text='Unidade de porções', max_length=20, verbose_name='Unidade de porções'),
        ),
    ]
